document.addEventListener( 'DOMContentLoaded', getLocalLang)

var arrLang = {
  eng: {
    Login: "Login",
    Register: "Register",
    Logout: "Logout",
    Items:"item",
    Home:"Home",
    Men:"Men",
    Women:"Women",
    Contact:"Contact",
    Tshirts:"T-shirts",
    Shirts:"Shirts",
    Turtleneck:"Turtleneck sweater",
    Jackets:"Jackets",
    Hoodies:"Hoodies",
    Sweatpants:"Sweatpants",
    Trousers:"Trousers",
    Bags:"Bags",
    Dresses:"Dresses",
    Blouses:"Blouses",
    Handbags:'Handbags',
    Skirts:'Skirts',
    Welcome:"Welcome to our online store! Our company welcomes everyone who came to the site!",
    Online:"Our online store offers the lowest prices, don't even try to find cheaper!",
    Wait:"We are waiting for you to shop every day, we are always at your service!",
    Learn:"Learn More",
    Released:"NEW RELEASED",
    Featured:"Featured Collections",
    More:"More INFO",
    Location:"Location",
    Shipping:"Shipping",
    Membership:"Membership",
    ContactUS:"CONTACT US",
    Contrary:"Mon-Fri from 8:00 to 16:00",
    Standart:"priemnaya.u.danila.i.romi@gmail.com",
    Office:"office:  +38 099 165 35 88",
    Newsletter:"Newsletter",
    SingUp:"Sign Up to get all news update and promo",
    Address:"Address",
    Send:"Send",
    SingUpl:"Sing Up",
    Person:"Personal infomation",
    Firstn:"Firsrt Name",
    Email:"Email Address",
    Singp:"Sign Up for Newsletter",
    LogInf:"Login Information",
    Password:"Password",
    Submit:"SUBMIT",
    Account:"Account",
    Discount:"discount",
    Create:"Create an account",
    101 :"White Tshirt",
    102: "Black Tshirt",
    104: "Blue Tshirt",
    105: "Empowered Tshirt",
    106: "Green Tshirt",
    107: "Red Tshirt",
    108: "Black Dress",
    110: "Black turtleneck with mark",
    111: "Black turtleneck",
    112: "Blue turtleneck",
    113: "Burgundy turtleneck",
    114: "Gray turtleneck",
    115: "Marsh turtleneck",
    116: "Laptop bag",
    118: "Black laptop bag",
    119: "Gray laptop bag",
    120: "Black bagpack",
    121: "Gray bagpack",
    122: "Black tshirt",
    123: "Blue shirt",
    124: "Gray shirt",
    125: "Plaid pink and blue shirt",
    126: "Plaid white and gray shirt",
    127: "Black jacket",
    128: "Brown jacket",
    129: "Red jacket",
    130: "Denim jacket",
    131: "White jacket",
    132: "Sandy jacket",
    133: "Black hoodie",
    134: "White hoodie",
    135: "Blue hoodie",
    136: "Orange hoodie",
    137: "Green hoodie",
    138: "Red hoodie",
    139: "Casual jeans",
    140: "White-gray jeans",
    141: "Gray jeans",
    142: "Black jeans",
    143: "Red dress",
    144: "Red-white dress",
    145: "Yellow dress",
    146: "White dress",
    147: "Blue dress",
    155: "Blue shirt",
    156: "Pink shirt",
    157: "White shirt",
    158: "Red plaid shirt",
    159: "Red-white shirt",
    160: "Black-white shirt",
    161: "Red blouse",
    162: "Black blouse",
    163: "Black-white blouse",
    164: "Pink blouse",
    165: "White blouse",
    166: "Black skirt",
    167: "Blue skirt",
    168: "Orange skirt",
    169: "Pink skirt",
    170: "Space skirt",
    171: "Denim skirt",
    172: "Brown blouse",
    173: "White shirt",
    174: "Red jacket",
    175: "Black jacket",
    176: "Yellow jacket",
    177: "Brown leather jacket",
    178: "Marsh jacket",
    179: "Gray jacket",
    180: "Purple trousers",
    181: "Leopard trousers",
    182: "Black trousers",
    183: "Denim trousers",
    184: "Ragged trousers",
    'White Tshirt': "Color: White; Material: 97% Cotton, 3% polyester;",
    'Black Tshirt': "Color: Black; Material: 97% Cotton, 3% polyester;",
    'Blue Tshirt': "Color: Blue; Material: 97% Cotton, 3% polyester;",
    'Empowered Tshirt': "Color: Empowered; Material: 97% Cotton, 3% polyester;",
    'Green Tshirt': "Color: Green; Material: 97% Cotton, 3% polyester;",
    'Red Tshirt': "Color: Red; Material: 97% Cotton, 3% polyester;",
    'Black Dress': "Color: Black; Fabric: Diving;",
    'Black turtleneck with mark': "Color: Black; Material: 90% polyamide 10% elastane;",
    'Black turtleneck': "Color: Black; Material: 90% polyamide 10% elastane;",
    'Blue turtleneck': "Color: Blue; Material: 90% polyamide 10% elastane;",
    'Burgundy turtleneck': "Color: Burgundy; Material: 90% polyamide 10% elastane;",
    'Gray turtleneck': "Color: Gray; Material: 90% polyamide 10% elastane;",
    'Marsh turtleneck': "Color: Marsh; Material: 90% polyamide 10% elastane;",
    'Laptop bag': "Color: Black; Material: Cotton + polyester;",
    'Black laptop bag': "Color: Black; Material: Cotton + polyester;",
    'Gray laptop bag': "Color: Gray; Materail: Cotton + polyester;",
    'Black bagpack': "Color: Black; Material: nylon;",
    'Gray bagpack': "Color: gray; material: nylon;",
    'Black shirt': "Color: black; material: cotton;",
    'Blue shirt': "Color: Blue; Material: cotton;",
    'Gray shirt': "Color: gray; material: cotton;",
    'Plaid pink and blue shirt': "Color: pink-blue; material: cotton;",
    'Plaid white and gray shirt': "Color: White-gray; Material: cotton;",
    'Black jacket': "Color: black; material: viscose + cotton;",
    'Brown jacket': "Color: Brown; Material: Viscose + cotton;",
    'Red jacket': "Color: Red; Material: Viscose + cotton",
    'Denim jacket': "Color: Blue; Material: Denim;",
    'White jacket': "Color: white; material: viscose + cotton;",
    'Sandy jacket': "Color: white; material: viscose + cotton;",
    'Black hoodie': "Color: black; material: cotton + polyester;",
    'White hoodie': "Color: white; material: cotton + polyester;",
    'Blue hoodie': "Color: Blue; Material: Cotton, polyester;",
    'Orange hoodie': "Color: orange; material: cotton, polyester;",
    'Green hoodie': "Color: Green; Material: Cotton + Polyester;",
    'Red hoodie': "Color: Red; Material: Cotton + Polyester;",
    'Casual jeans': "Material: denim;",
    'White-gray jeans': "Color: White-gray; Material: denim;",
    'Gray jeans': "Color: gray; material: denim;",
    'Black jeans': "Color: gray; material: denim;",
    'Red dress': "Color: Red; Material: Chiffon;",
    'Red-white dress': "Color: Red-white; Material: guipure;",
    'Yellow dress': "Color: yellow; material: cotton;",
    'White dress': "Color: white; material: cotton;",
    'Blue dress': "Color: Blue; Material: cotton;",
    'Blue shirt': "Color: Blue; Material: cotton;",
    'Pink shirt': "Color: pink; material: cotton;",
    'White shirt': "Color: white; material: cotton;",
    'Red plaid shirt': "Color: Red; Material: cotton;",
    'Red-white shirt': "Color: red-white; material: cotton;",
    'Black-white shirt': "Color: Black-white; Material: cotton;",
    'Red blouse': "Color: Red; Material: Synthetic;",
    'Black blouse': "Color: black; material: synthetic;",
    'Black-white blouse': "Color: black and white; material: synthetic;",
    'Pink blouse': "Color: Pink; Material: Cotton;",
    'White blouse': "Color: white; material: cotton;",
    'Black skirt': "Color: Black; Material: Leather;",
    'Blue skirt': "Color: Blue; Material: jacquard;",
    'Orange skirt': "Color: orange; material: synthetic;",
    'Pink skirt': "Color: pink; material: synthetic;",
    'Space skirt': "Color: space Material: synthetic;",
    'Denim skirt': "Material: denim;",
    'Brown blouse': "Color: Brown; Material: Synthetic;",
    'White shirt': "Color: black; material: cotton;",
    'Red jacket': "Color: red; material: viscose + cotton",
    'Black jacket': "Color: black; material: viscose + cotton",
    'Yellow jacket': "Color: Red; Material: cotton",
    'Brown leather jacket': "Color: Brown; Material: Leather;",
    'Marsh jacket': "Color: green; material: viscose + cotton;",
    'Gray jacket': "Color: gray; material: leather;",
    'Purple trousers': "Color: Pink; Material: Cotton;",
    'Leopard trousers': "Color: Leopard; Material: polyester;",
    'Black trousers': "Color: black; material: cotton + viscose;",
    'Denim trousers': "Material: denim;",
    'Ragged trousers': "Material: denim;",
    Special:'Special offers',
    Backpacks:'Backpacks | Gucci',
    Wristwatch:'Wristwatch | MAD Paris',
    Belt:'Leather Belt | Giorgio Armani',
    Handmade:'Silk tie | Stefano Ricci',
    Lace:'Lace blouse | Dolce & Gabbana',
    Skirt_p:'Skirt | Valentino',
    Dress_p:'Dress | Dolce&Gabbana',
    Chronograph:'Chronograph watch | Korloff',
    Billing:'Billing Address',
    City:'City',
    State:'State',
    Ind:"Zip",
    Payment:'Payment',
    Accepted:'Accepted Cards',
    Namec:"Name on Card",
    Credit:"Credit card number",
    Exp:"Exp Month",
    Expy:"Exp Year",
    Pay:"Pay",
    Delete:"Delete Item",
    Bag:"Bag is empty",
    Total:"Total",
    Confirm:"Confirm order",
    Shop:"My Shopping Bag",
    Add:"Add to bag",
    Register_Login:"Register\login to add to cart",
    Bag:"Bag is empty",
    Count:"Count - ",
    SuccesOrd:"Order successfully received!",
    Danil:"Our supplier Daniel will find you and give the purchase",
  },
  ukr: {
    Login: "Логін",
    Register: "Реєстрація",
    Logout: "Вихід",
    Items:"Товар",
    Home:"Головна",
    Men:"Чоловіки",
    Women:"Жінки",
    Contact:"Контакти",
    Tshirts:"Футболки",
    Shirts:"Сорочки",
    Turtleneck:"Гольфи",
    Jackets:"Куртки",
    Hoodies:"Толстовки",
    Sweatpants:"Спортивні штани",
    Trousers:"Штани",
    Bags:"Сумки",
    Dresses:"Сукні",
    Blouses:"Блузки",
    Handbags:'Жіночі сумки',
    Skirts:'Спідниці',
    Welcome:"Ласкаво просимо в наш інтернет-магазин! Наша компанія вітає всіх, хто зайшов на сайт!",
    Online:"Наш інтернет-магазин пропонує найнижчі ціни, навіть не намагайтеся знайти дешевше!",
    Wait:"Ми чекаємо вас на покупки щодня, ми завжди до ваших послуг!",
    Learn:"Детальніше",
    Released:"Новинки",
    Featured:"ОСОБЛИВІ КОЛЕКЦІЇ",
    More:"Більше інформації",
    Location:"Місце знаходження",
    Shipping:"Доставка",
    Membership:"Співтовариство",
    ContactUS:"Зв'язок з нами",
    Contrary:"пн.-пт c 8:00 до 16:00",
    Standart:"priemnaya.u.danila.i.romi@gmail.com",
    Office:"Номер компанії:  +38 099 165 35 88",
    Newsletter:"Розсилка",
    SingUp:"Увійдіть, щоб отримувати всі новини і промо",
    Address:"Адреса",
    Send:"Відправити",
    SingUpl:"Зареєструватися",
    Person:"Персональна інформація",
    Firstn:"Ім'я",
    Email:"Email адреса",
    Singp:"Підписатися на розсилку",
    LogInf:"Логін інформація",
    Password:"Пароль",
    Submit:"Зареєструватись",
    Account:"Обліковий запис",
    Discount:"Знижка",
    Create:"Створення обікового запису",
    101 :"Біла футболка",
    102: "Чорна футболка",
    104: "Синя футболка",
    105: "Футболка 'Empowered'",
    106: "Зелена футболка",
    107: "Червона футболка",
    108: "Чорна сукня",
    110: "Чорний гольф з позначкою",
    111: "Чорний гольф",
    112: "Синій гольф",
    113: "Червоний гольф",
    114: "Сірий гольф",
    115: "Болотний гольф",
    116: "Сумка для ноутбуку",
    118: "Чорна сумка для ноутбуку",
    119: "Сіра сумка для ноутбуку",
    120: "Чорний рюкзак",
    121: "Сірий рюкзак",
    122: "Чорна сорочка",
    123: "Синя сорочка",
    124: "Сіра сорочка",
    125: "Клітчата сорочка синьо-рожева",
    126: "Біло-сіра клітчата сорочка",
    127: "Чорна куртка",
    128: "Коричнева куртка",
    129: "Червона куртка",
    130: "Джинсова куртка",
    131: "Біла куртка",
    132: "Піщана куртка",
    133: "Чорна толстовка",
    134: "Біла толстовка",
    135: "Синя толстовка",
    136: "Помаранчева толстовка",
    137: "Зелена толстовка",
    138: "Червона толстовка",
    139: "Джинси",
    140: "Біло-сірі джинси",
    141: "Сірі джинси",
    142: "Чорні джинми",
    143: "Червона сукня",
    144: "Червоно-біла сукня",
    145: "Жовта сукня",
    146: "Біла сукня",
    147: "Синя сукня",
    155: "Синя сорочка",
    156: "Рожева сорочка",
    157: "Біла сорочка",
    158: "Клітчата червона сорочка",
    159: "Червоно-біла сорочка",
    160: "Чорно-біла сорочка",
    161: "Червона блузка",
    162: "Чорна блузка",
    163: "Чорно-біла блузка",
    164: "Рожева блузка",
    165: "Біла блузка",
    166: "Чорна спідниця",
    167: "Синя спідниця",
    168: "Помаранчева спідниця",
    169: "Рожева спідниця",
    170: "'Галактична' спідниця",
    171: "Джинсова спідниця",
    172: "Коричнева спідниця",
    173: "Біла сорочка",
    174: "Червона куртка",
    175: "Чорна куртка",
    176: "Жовта куртка",
    177: "Коричнева кожана куртка",
    178: "Болотна куртка",
    179: "Сіра куртка",
    180: "Фіолетові штани",
    181: "Леопардові штани",
    182: "Чорні штани",
    183: "Джинсові штани",
    184: "Рвані штани",
    'White Tshirt': "Колір: білий; матеріал: 97% бавовна, 3% поліестер;",
    'Black Tshirt': "Колір: чорний; матеріал: 97% бавовна, 3% поліестер;",
    'Blue Tshirt': "Колір: Синій; Матеріал: 97% бавовна, 3% поліестер;",
    'Empowered Tshirt': "Колір: посилений; Матеріал: 97% бавовна, 3% поліестер;",
    'Green Tshirt': "Колір: зелений; матеріал: 97% бавовна, 3% поліестер;",
    'Red Tshirt': "Колір: Червоний; Матеріал: 97% бавовна, 3% поліестер;",
    'Black Dress': "Колір: чорний; тканина: дайвінг;",
    'Black turtleneck with mark': "Колір: Чорний; Матеріал: 90% поліамід 10% еластан",
    'Black turtleneck': "Колір: Чорний; Матеріал: 90% поліамід 10% еластан;",
    'Blue turtleneck': "Колір: Синій; Матеріал: 90% поліамід 10% еластан;",
    'Burgundy turtleneck': "Color: Burgundy; Material: 90% polyamide 10% elastane;",
    'Gray turtleneck': "Колір: сірий; матеріал: 90% поліамід 10% еластан;",
    'Marsh turtleneck': "Колір: Марш; Матеріал: 90% поліамід, 10% еластан;",
    'Laptop bag': "Колір: чорний; матеріал: бавовна + поліестер;",
    'Black laptop bag': "Колір: чорний; матеріал: бавовна + поліестер;",
    'Gray laptop bag': "Колір: сірий; матеріал: бавовна + поліестер;",
    'Black bagpack': "Колір: чорний; матеріал: нейлон;",
    'Gray bagpack': "Колір: сірий; матеріал: нейлон;",
    'Black shirt': "Колір: чорний; матеріал: бавовна;",
    'Blue shirt': "Колір: Синій; Матеріал: бавовна;",
    'Gray shirt': "Колір: сірий; матеріал: бавовна;",
    'Plaid pink and blue shirt': "Колір: рожево-блакитний; матеріал: бавовна;",
    'Plaid white and gray shirt': "Колір: Біло-сірий; Матеріал: бавовна;",
    'Black jacket': "Колір: чорний; матеріал: віскоза + бавовна;",
    'Brown jacket': "Колір: Коричневий; Матеріал: Віскоза + бавовна;",
    'Red jacket': "Колір: Червоний; Матеріал: Віскоза + бавовна",
    'Denim jacket': "Колір: Синій; Матеріал: Джинсовий;",
    'White jacket': "Колір: білий; матеріал: віскоза + бавовна;",
    'Sandy jacket': "Колір: білий; матеріал: віскоза + бавовна;",
    'Black hoodie': "Колір: чорний; матеріал: бавовна + поліестер;",
    'White hoodie': "Колір: білий; матеріал: бавовна + поліестер;",
    'Blue hoodie': "Колір: Синій; Матеріал: Бавовна, поліестер;",
    'Orange hoodie': "Колір: помаранчевий; матеріал: бавовна, поліестер;",
    'Green hoodie': "Колір: Зелений; Матеріал: Бавовна + поліестер;",
    'Red hoodie': "Колір: Червоний; Матеріал: Бавовна + поліестер;",
    'Casual jeans': "Матеріал: денім;",
    'White-gray jeans': "Колір: Біло-сірий; Матеріал: денім;",
    'Gray jeans': "Колір: сірий; матеріал: денім;",
    'Black jeans': "Колір: сірий; матеріал: денім;",
    'Red dress': "Колір: Червоний; Матеріал: Шифон;",
    'Red-white dress': "Колір: Червоно-білий; Матеріал: гіпюр;",
    'Yellow dress': "Колір: жовтий; матеріал: бавовна;",
    'White dress': "Колір: білий; матеріал: бавовна;",
    'Blue dress': "Колір: Синій; Матеріал: бавовна;",
    'Blue shirt': "Колір: Синій; Матеріал: бавовна;",
    'Pink shirt': "Колір: рожевий; матеріал: бавовна;",
    'White shirt': "Колір: білий; матеріал: бавовна;",
    'Red plaid shirt': "Колір: Червоний; Матеріал: бавовна;",
    'Red-white shirt': "Колір: червоно-білий; матеріал: бавовна;",
    'Black-white shirt': "Колір: Чорно-білий; Матеріал: бавовна;",
    'Red blouse': "Колір: Червоний; Матеріал: Синтетичний;",
    'Black blouse': "Колір: чорний; матеріал: синтетичний;",
    'Black-white blouse': "Колір: чорно-білий; матеріал: синтетичний;",
    'Pink blouse': "Колір: Рожевий; Матеріал: Бавовна;",
    'White blouse': "Колір: білий; матеріал: бавовна;",
    'Black skirt': "Колір: Чорний; Матеріал: Шкіра;",
    'Blue skirt': "Колір: Синій; Матеріал: жаккард;",
    'Orange skirt': "Колір: помаранчевий; матеріал: синтетичний;",
    'Pink skirt': "Колір: рожевий; матеріал: синтетичний;",
    'Space skirt': "Колір: простір Матеріал: синтетичний;",
    'Denim skirt': "Матеріал: денім;",
    'Brown blouse': "Колір: Коричневий; Матеріал: Синтетичний;",
    'White shirt': "Колір: чорний; матеріал: бавовна;",
    'Red jacket': "Колір: червоний; матеріал: віскоза + бавовна",
    'Black jacket': "Колір: чорний; матеріал: віскоза + бавовна",
    'Yellow jacket': "Колір: Червоний; Матеріал: бавовна",
    'Brown leather jacket': "Колір: Коричневий; Матеріал: Шкіра;",
    'Marsh jacket': "Колір: зелений; матеріал: віскоза + бавовна;",
    'Gray jacket': "Колір: сірий; матеріал: шкіра;",
    'Pink trousers': "Колір: Рожевий; Матеріал: Бавовна;",
    'Leopard trousers': "Колір: Леопард; Матеріал: поліестер;",
    'Black trousers': "Колір: чорний; матеріал: бавовна + віскоза;",
    'Denim trousers': "Матеріал: денім;",
    'Ragged trousers': "Матеріал: денім;",
    Special:'Спец. пропозиції',
    Backpacks:'Сумки | Gucci',
    Wristwatch:'Наручний годинник | MAD Paris',
    Belt:'Шкіряний ремінь | Giorgio Armani',
    Handmade:'Шовкова краватка | Stefano Ricci',
    Lace:'Блузка | Dolce & Gabbana',
    Skirt_p:'Спідниця | Valentino',
    Dress_p:'Плаття | Dolce&Gabbana',
    Chronograph:'Хронограф годинник | Korloff',
    Billing:'Адреса виставлення рахунку',
    City:'Місто',
    State:'Область',
    Ind:"Індекс",
    Payment:'Оплата',
    Accepted:'Приймаються картки',
    Namec:"Ім'я на картці",
    Credit:"Номер картки",
    Exp:"Місячний термін",
    Expy:"Річний термін",
    Pay:"Сплатити",
    Delete:"Видалити товар",
    Bag:"Корзина порожня",
    Total:"Заг. вартість",
    Confirm:"Підтвердити замовлення",
    Shop:"Корзина",
    Add:"Додати у кошик",
    Register_Login:"Зареєструйтеся або залогіньтесь",
    Bag:"Корзина порожня",
    Count:"Кількість - ",
    SuccesOrd:"Замовлення було отримано!",
    Danil:"Наш директор Данило, незабаром з вами зв'яжеться",
  },
};

$(function () {
  $(".translate").click(function () {
    var lang = $(this).attr("id");
    saveLocalLang(lang);
    
    $(".lang").each(function (index, item) {
      $(this).text(arrLang[lang][$(this).attr("key")]);
    });
  });
});

// LOCAL STORAGE

function saveLocalLang(language){
  let langs
  if(localStorage.getItem('langs') === null){
    langs=[]
  }
  else{
    langs = JSON.parse(localStorage.getItem('langs'))
  }
  langs.push(language);
  localStorage.setItem('langs', JSON.stringify(langs));
}

function getLocalLang(language){
  let langs;
  if(localStorage.getItem('langs') === null){
    langs = []
  }
  else{
    langs = JSON.parse(localStorage.getItem('langs'));
  }
  langs.forEach(function(language){
    let lang = langs[langs.length - 1]
    setTimeout(()=> {
      $('.lang').each(function(index,item){
        $(this).text(arrLang[lang][$(this).attr('key')]);
      });
    },0)
  })
}